import './globals.css'
import { Inter } from 'next/font/google'
import ThemeRegistry from '../themes/themeRegistry';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Chris App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry options={{key: 'mui-style'}}>
      <body className={inter.className}>
          {children}
      </body>
      </ThemeRegistry>
    </html>
  )
}
